version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - JWT_SECRET_KEY=dev_secret_key
      # Uncomment and set these with your actual Cloudinary credentials when testing
      # - CLOUDINARY_CLOUD_NAME=your_cloud_name
      # - CLOUDINARY_API_KEY=your_api_key
      # - CLOUDINARY_API_SECRET=your_api_secret
    volumes:
      - .:/app
    restart: unless-stopped
