services:
  - type: web
    name: itimeline-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: itimeline-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://i-timeline.com  # You'll update this later
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: itimeline-db
    databaseName: itimeline
    plan: free
